version: "1.0"

x-logging:
  &default-logging
      driver: json-file
      options:
        max-size: 10m

services:
  api:
    restart: always
    container_name: ais_api_dev
    working_dir: /ais_api
    env_file:
      ../.env.dev
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    networks:
      - quick-start_back_end
    logging: *default-logging
    volumes:
      - ..:/ais_api
    healthcheck:
      test: curl http://localhost:${PORT}/ready
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  quick-start_back_end:
    name: quick-start_back_end
    external: true
